# -*- coding: utf-8 -*-
"""GP_project_Colab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGNXlydcYgFRoAd6NC_EZtLdbv5MM7kk

# New Section
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install dominate

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My\ Drive/GP_Project/Realistic_Face/

# Commented out IPython magic to ensure Python compatibility.
# %mkdir trained
# %mkdir trained/w
# %mkdir datasets/w/test_A

!python test.py --dataroot /content/drive/My\ Drive/pix2pixHD-colab/pix2pixHD/datasets/w --name w --netG global --resize_or_crop none --label_nc 0 --no_instance --how_many 13 --checkpoints_dir ./trained --which_epoch 30

!python train.py --label_nc 0 --no_instance --name w --dataroot /content/drive/My\ Drive/pix2pixHD-colab/pix2pixHD/datasets/w --continue_train --display_freq 100 --checkpoints_dir /content/drive/My\ Drive/pix2pixHD-colab/pix2pixHD/checkpoints --which_epoch latest --save_epoch_freq 10